config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  get 'home/index'
  resources :events
  resources :sports
  root to: "home#index"

  devise_for :users

  resources :users, only: [:edit] do
    member do
      get :profile
    end
    collection do
      get :products
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/sport.rb
class Sport < ApplicationRecord
    has_many :event
end

app/controllers/sports_controller.rb
class SportsController < ApplicationController

before_action :authenticate_user!

before_action :set_sport, only: [:show, :edit, :update, :destroy]

 def index
   @sports = Sport.all
 end

 def show
 end

 def new
   @sport = Sport.new
 end
 
 def edit
 end

 def create
   @sport = Sport.new(sport_params)
   respond_to do |format|
     if @sport.save
       format.html { redirect_to @sport, notice: 'Sport was successfully created.' }
       format.json { render :show, status: :created, location: @sport}
     else
       format.html { render :new }
       format.json { render json: @sport.errors, status: :unprocessable_entity }
     end
   end
 end

 def update
   respond_to do |format|
     if @sport.update(sport_params)
       format.html { redirect_to @sport, notice: 'Sport was successfully updated.' }
       format.json { render :show, status: :ok, location: @sport }
     else
       format.html { render :edit }
       format.json { render json: @sport.errors, status: :unprocessable_entity }
     end
   end
 end

 def destroy
   @sport.destroy
   respond_to do |format|
     format.html { redirect_to sports_url, notice: 'Sport was successfully destroyed.' }
     format.json { head :no_content }
   end
 end
 private

   def set_sport
     @sport = Sport.find(params[:id])
   end

   def sport_params
     params.require(:sport).permit(:name, :category)
   end

end

app/views/sports/_form.html.erb
<%= form_with(model: sport, local: true) do |form| %>
  <% if sport.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sport.errors.count, "error") %> prohibited this sport from being saved:</h2>

      <ul>
      <% sport.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
    <div class="field">
    <%= form.label :category %>
    <%= form.text_field :category %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/sports/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', sport: @sport %>

<%= link_to 'Show', @sport %> |
<%= link_to 'Back', sports_path %>

app/views/sports/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sports</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sports.each do |sport| %>
      <tr>
        <td><%= sport.name%></td>
        <td><%= sport.category%></td>
        <td><%= link_to 'Show', sport %></td>
        <td><%= link_to 'Edit', edit_sport_path(sport) %></td>
        <td><%= link_to 'Destroy', sport, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New sport', new_sport_path %>

app/views/sports/new.html.erb
<h1>New Sport</h1>

<%= render 'form', sport: @sport %>

<%= link_to 'Back', sports_path %>

app/views/sports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @sport.name %>
</p>

<%= link_to 'Edit', edit_sport_path(@sport) %> |
<%= link_to 'Back', sports_path %>